spring:
  config:
    import:
      - classpath:application-server.yml
      - classpath:application-db.yml
      - classpath:application-jwt.yml
      - classpath:application-producer.yml
      - classpath:application-consumer.yml
      - classpath:spy.properties
      - classpath:application-actuator.yml
  jpa:
    open-in-view: false
