spring:
  config:
    import:
      - classpath:application-server.yml
      - classpath:application-jwt.yml
      - classpath:application-db.yml
      - classpath:application-upload.yml
      - classpath:application-producer.yml
